name: CD - Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Instalar Angular CLI (caso não esteja globalmente disponível)
        run: npm install -g @angular/cli

      - name: Criar build do Angular
        run: ng build --configuration=production

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Enviar arquivos para o S3
        run: aws s3 sync dist/fake-twitter-frontend s3://fake-twitter-frontend --delete

      - name: Invalidar cache do CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
